baseurl      = "https://loonaire.github.io/"
title        = "Loonaire Blog"
author 		 = "Loonaire"
languageCode = "fr-fr"
theme        = "holy"
canonifyURLs = true
relativeURLs = true
defaultContentLanguage = "fr"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[params]
  dateform        = "2 January 2006"
  dateformShort   = "2 January"
  dateformNum     = "02/01/2006"
  dateformNumTime = "02/01/2006 15:04"
  
  #Copyright
  copyright = "copyright ©Loonaire"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "A propos"
    url = "/about"
    weight = 3

  [[menu.main]]
    identifier = "other"
    name = "Autre contenu"
    url = "/other/"
    weight = 2

[languages]
[languages.fr]
[languages.en.params]
  landingPageName = "Accueil"
